# Generated by Django 5.0.1 on 2024-02-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('fio', models.CharField(max_length=70)),
                ('passSeries', models.CharField(max_length=4)),
                ('passNum', models.CharField(max_length=6)),
                ('passHome', models.CharField(max_length=200)),
                ('passDate', models.DateField()),
                ('passCode', models.CharField(max_length=8)),
                ('registration', models.CharField(max_length=250)),
                ('postIndex', models.CharField(max_length=10)),
                ('inn', models.CharField(max_length=20)),
                ('snils', models.CharField(max_length=15)),
                ('clientMail', models.EmailField(max_length=254)),
                ('clientPhone', models.CharField(max_length=20)),
                ('bank_rs_num', models.CharField(max_length=20)),
                ('bankName', models.CharField(max_length=50)),
                ('bankBik', models.CharField(max_length=10)),
                ('bank_ks_num', models.CharField(max_length=20)),
                ('bankKpp', models.CharField(max_length=10)),
                ('bankInn', models.CharField(max_length=10)),
                ('doverenost', models.CharField(default='', max_length=15)),
                ('the_end_of_dever', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('lotNum', models.CharField(max_length=30)),
                ('docPrice', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferst.client')),
            ],
        ),
    ]
