# Generated by Django 5.0.1 on 2024-02-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctioninfo',
            options={'verbose_name': 'Информация об аукционе', 'verbose_name_plural': 'Информация об аукционах'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferst.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='docPrice',
            field=models.IntegerField(verbose_name='Цена документа'),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='lotNum',
            field=models.CharField(max_length=30, verbose_name='Номер лота'),
        ),
        migrations.AlterField(
            model_name='auctioninfo',
            name='url',
            field=models.CharField(max_length=150, verbose_name='URL аукциона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankBik',
            field=models.CharField(max_length=10, verbose_name='БИК банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankInn',
            field=models.CharField(max_length=10, verbose_name='ИНН банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankKpp',
            field=models.CharField(max_length=10, verbose_name='КПП банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankName',
            field=models.CharField(max_length=50, verbose_name='Название банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_ks_num',
            field=models.CharField(max_length=20, verbose_name='К/С номер участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_rs_num',
            field=models.CharField(max_length=20, verbose_name='Р/С номер участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город создания договора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientMail',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта клиента участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientPhone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона клиента участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='doverenost',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Доверенность'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fio',
            field=models.CharField(max_length=70, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=20, verbose_name='ИНН клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passCode',
            field=models.CharField(max_length=8, verbose_name='Код подразделения паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passDate',
            field=models.DateField(verbose_name='Дата выдачи паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passHome',
            field=models.CharField(max_length=200, verbose_name='Орган выдавший паспорт клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passNum',
            field=models.CharField(max_length=6, verbose_name='Номер паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passSeries',
            field=models.CharField(max_length=4, verbose_name='Серия паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postIndex',
            field=models.CharField(max_length=10, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration',
            field=models.CharField(max_length=250, verbose_name='Прописка клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='snils',
            field=models.CharField(max_length=15, verbose_name='СНИЛС клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='the_end_of_dever',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания доверенности'),
        ),
    ]
