# Generated by Django 5.0.1 on 2024-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0002_alter_auctioninfo_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город создания договора'),
        ),
    ]
