# Generated by Django 5.0.1 on 2024-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0003_alter_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bankBik',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='БИК банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankInn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankKpp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='КПП банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bankName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название банка участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_ks_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='К/С номер участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_rs_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Р/С номер участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientMail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта клиента участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientPhone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона клиента участника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passCode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Код подразделения паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passHome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Орган выдавший паспорт клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passNum',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passSeries',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postIndex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Прописка клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='snils',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='СНИЛС клиента'),
        ),
    ]
