# Generated by Django 5.0.1 on 2024-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0004_alter_client_bankbik_alter_client_bankinn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passDate',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Дата выдачи паспорта клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='the_end_of_dever',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Дата окончания доверенности'),
        ),
    ]
