# Generated by Django 5.0.1 on 2024-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0005_alter_client_passdate_alter_client_the_end_of_dever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fio',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя клиента'),
        ),
    ]
